# "Application Deployment" is a GitHub Actions workflow that facilitates the
# deployment of your application into different environments. The workflow is
# manually triggered and an environment requires specification. It sets up Node.js on
# an Ubuntu environment, conducts unit and integration tests, builds the application,
# and deploys it on Azure Functions if requested.

name: Application deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: environment
        default: dev # dev, qa, prod
      deploy:
        required: true
        type: boolean
        default: false 

run-name: ${{ inputs.environment }} Application deployment

env:
  NODE_VERSION: '18.x'
  AZURE_FUNCTIONAPP_NAME: 'func-dc-${{inputs.environment}}'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  Build:
    runs-on: ubuntu-22.04
    name: ${{ inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        shell: pwsh
        run: |
          npm install

      - name: Build
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm run build --if-present
          npm prune --production
          popd

      - name: Deploy Azure Function
        if: ${{ inputs.deploy == true }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: '${{ secrets.AZURE_DC_FUNCTIONAPP_PUBLISH_PROFILE }}'
