# "Post Release" is a GitHub Actions workflow that automates releasing new versions
# of your project every time a push to the main branch is made. It uses Node.js version
# 18.x on the latest Ubuntu environment and employs semantic-release for versioning

name: Post Release
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '18.x'

jobs:
  release:
    name: postRelease
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: setup-node
        name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - id: clean-install
        name: Clean install
        run: npm install
      - id: semantic-release
        name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: npx semantic-release
